services:
  redis:
    cpus: 8.0
    mem_limit: 4096m
    restart: always
    pull_policy: if_not_present
    image: redis:8.2
    container_name: redis
    command: >
      redis-server
      --requirepass ${password}
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
    volumes:
      - ./files/redis:/data
    ports:
      - "6379:6379"
    networks:
      - imahs-oss

  # python:3.13
  python:
    pull_policy: missing
    image: python:3.13
  # imahs-oss
  imahs-oss:
    depends_on:
      - python
    pull_policy: never
    restart: always
    container_name: imahs-oss
    image: imahs:oss
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - ./files:/imahs-oss/files
      - ./files/cache/datalab:/root/.cache/datalab
networks:
  imahs-oss:
    driver: bridge
