#!/bin/bash

PASSWORD=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --password) PASSWORD="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

echo "PASSWORD: $PASSWORD"

if ! command -v docker &> /dev/null; then
  echo "install docker engine following the instructions at https://docs.docker.com/engine/install/"
  exit 1
fi

docker system prune -f 
docker container prune -f 
docker image prune -f 
password=$PASSWORD docker compose -f servers/docker-compose.yml down --remove-orphans
password=$PASSWORD docker compose -f servers/docker-compose.yml up   -d --build --force-recreate
password=$PASSWORD docker compose -f servers/docker-compose.yml logs -f

password=$PASSWORD docker compose -f imahs/docker-compose.yml down --remove-orphans
password=$PASSWORD docker compose -f imahs/docker-compose.yml up   -d --build --force-recreate
password=$PASSWORD docker compose -f imahs/docker-compose.yml logs -f