services:
  # python:3.13
  python:
    pull_policy: missing
    image: python:3.13
  # imahs-oss
  imahs-oss:
    depends_on:
      - python
    pull_policy: never
    ports:
      - "8118:8118"
    restart: always
    container_name: imahs-oss
    image: imahs:oss
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      - redis_host=${HOST_IP}
      - redis_client=imahs
      - redis_password=${password}
      - redis_channel=imahs:oss
    volumes:
      - ./files:/imahs-oss/files
networks:
  imahs-oss:
    driver: bridge
