FROM python:3.13 As deps
WORKDIR                    /imahs
COPY   ./requirements.txt  /imahs/requirements.txt
RUN apt update && apt install -y --no-install-recommends supervisor && apt clean
RUN pip install --no-cache-dir -r requirements.txt

FROM deps
WORKDIR                 /imahs
RUN            mkdir -p /imahs/app/  /imahs/lib/ 
COPY      ./app/        /imahs/app/
COPY      ./lib/        /imahs/lib/ 
COPY   ./supervisord.conf  /imahs/supervisord.conf
CMD ["supervisord", "-c", "/imahs/supervisord.conf"]