FROM python:3.13 AS deps
RUN apt update && apt upgrade -y --no-install-recommends && apt clean -y
RUN pip install --no-cache-dir marker-pdf uvicorn fastapi python-multipart

FROM deps
CMD ["marker_server", "--host", "0.0.0.0", "--port", "8192"]
