FROM python:3.12 AS deps
RUN apt update && apt upgrade -y --no-install-recommends && apt clean -y
RUN pip install --no-cache-dir libretranslate

FROM deps
CMD ["libretranslate", "--load-only", "en,it", "--host", "0.0.0.0", "--port", "8193"]
